name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev scons libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip
        cd $GITHUB_WORKSPACE/../
        git clone --recursive https://github.com/godotengine/godot-cpp.git -b 3.3
        cd godot-cpp
        scons platform=linux generate_bindings=yes target=debug
        cd ../
        git clone https://github.com/godotengine/godot.git -b 3.3
        cd $GITHUB_WORKSPACE
        make foreigner.so
        make foreigner.dll
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          foreigner.so
          foreigner.dll
